<?php

namespace Game;

class Mage extends Character
{
    private int $originalMana;
    private int $mana;

    public function __construct(string $name, string $role, int $health, int $attack, int $defense = 3, int $range = 5, int $mana = 150)
    {
        parent::__construct($name, $role, $health, $attack, $defense, $range);
        $this->mana = $mana;
        $this->specialAttacks = ['fireBall, frostNova'];
        $this->originalMana = $mana;
    }

    public function setMana(int $mana): void
    {
        $this->mana = $mana;
    }

    public function getMana(): int
    {
        return $this->mana;
    }

    public function castFireball(): string
    {
        if ($this->mana <= 30) {
            return "Not enough magic";
        }

        $attackMod = $this->attack * 1.5;
        $defenseMod = $this->defense - ($this->defense * 0.8);
        $modResult = $this->modifyTemporaryStats($attackMod, $defenseMod);
        $this->mana -= 30;

        return "Fireball attack performed. $modResult";
    }

    public function castFrostNova(): string
    {
        if ($this->mana < 45) {
            return "Not enough rage to perform Whirlwind!";
        }

        $attackMod = $this->attack * 0.4;
        $defenseMod = $this->defense * 1.2;

        $this->mana -= 45;

        $modResult = $this->modifyTemporaryStats($attackMod, $defenseMod);

        return "Frost nova performed! $modResult";
    }


    public function executeSpecialAttacks(string $attackName): string
    {
        switch ($attackName) {
            case 'fireBall':
                return $this->castFireball();
            case 'frostNova':
                return $this->castFrostNova();
            default:
                return "Unknown special attack: {$attackName}";
        }
    }

    public
    function resetAttributes(): void
    {
        $this->mana = $this->originalMana;
    }


    public
    function getSummary(): string
    {
        $summary = parent::getSummary(); // TODO: Change the autogenerated stub
        $manaStatus = "This Mage commands {$this->mana}  mana for fireball";
        return $summary . $manaStatus;
    }

}
