<?php

namespace Game;

use Game\Character;

class Rogue extends Character
{
    private int $originalEnergy;
    private int $energy = 100;

    public function __construct(string $name, string $role, int $health, int $attack, int $defense = 4, int $range = 2, int $energy = 100)
    {
        parent::__construct($name, $role, $health, $attack, $defense, $range);
        $this->originalEnergy = $energy;
        $this->specialAttacks = ['sneakAttack', 'poisonDagger'];
        $this->energy = $energy;

    }


    /**
     * @return int
     */
    public function getEnergy(): int
    {
        return $this->energy;
    }

    /**
     * @param int $energy
     * @return void
     */
    public function setEnergy(int $energy): void
    {
        $this->energy = $energy;
    }

    public function performSneakAttack(): string
    {
        if ($this->energy >= 20) {
            $this->energy -= 20;

            // Bereken de tijdelijke stats
            $attackMod = $this->attack * 2;
            $defenseMod = $this->defense - (40 * 0.6);

            // Gebruik de protected methode
            $modResult = $this->modifyTemporaryStats($attackMod, $defenseMod);

            return "Sneak attack performed. $modResult";
        }

        return "Not enough energy.";
    }

    public function usePoisonDagger(): string
    {
        if ($this->energy < 30) {
            return "Not enough energy to perform Whirlwind!";
        }

        $attackMod = $this->attack * 0.8;
        $defenseMod = $this->defense * 0.7;

        $this->energy -= 30;

        $modResult = $this->modifyTemporaryStats($attackMod, $defenseMod);

        return "Poison dagger performed! $modResult";
    }

    public function resetAttributes(): void
    {
     $this->energy = $this->originalEnergy;  // TODO: Implement resetAttributes() method.
    }

    public function executeSpecialAttacks(string $attackName): string
    {
        switch ($attackName) {
            case 'sneakAttack':
                return $this->performSneakAttack();

            case 'poisonDagger':
                return $this->usePoisonDagger();

            default:
                return "Unknown special attack: {$attackName}";
        }
    }


    public function getSummary(): string
    {
        $summary = parent::getSummary(); // TODO: Change the autogenerated stub
        $energyStatus = "This rogue has {$this->energy} energy left";
        return $summary . $energyStatus;
    }

}